apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: redis
    name: redis
  spec:
    replicas: 3
    selector:
      app: redis
    template:
      metadata:
        labels:
          app: redis
      spec:
        containers:
        - env:
            - name: REDIS_DATA_MAX_AGE
              value: ${REDIS_DATA_MAX_AGE}
            - name: REDIS_SENTINEL_SERVICE_HOST
              value: redis-sentinel
            - name: REDIS_SENTINEL_SERVICE_PORT
              value: ${REDIS_SENTINEL_SERVICE_PORT}
            - name: REDIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ${REDIS_IMAGE}
          imagePullPolicy: Always
          name: redis
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: data
          ports:
            - containerPort: 6379
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: ${REDIS_PV}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: ${REDIS_IMAGE}:${REDIS_IMAGE_TAG}
          namespace: ${REDIS_IMAGE_NAMESPACE}
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: redis
    name: redis
  spec:
    ports:
      - port: 6379
        targetPort: 6379
    selector:
      app: redis

parameters:
- name: REDIS_DATA_MAX_AGE
  description: Maximal age of slave data directories in days.
  required: true
  value: "4"
- name: REDIS_IMAGE
  description: Location and name of the Redis Sentinel image.
  required: true
  value: redis-ha
- name: REDIS_IMAGE_NAMESPACE
  description: Namespace to find the Redis image.
  required: true
  value: hdhclr-tools
- name: REDIS_IMAGE_TAG
  description: Tag to use for the Redis image.
  required: true
- name: REDIS_PV
  description: Name of the Redis PV to bind.
  required: true
  value: redis-storage
- name: REDIS_SENTINEL_SERVICE_PORT
  description: Port of the redis sentinel service
  required: true
  value: "26379"
