apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: redis-master
      redis-master: "true"
      redis-sentinel: "true"
      role: master
    name: redis-master
  spec:
    replicas: 1
    selector:
      app: redis-master
      redis-master: "true"
      redis-sentinel: "true"
      role: master
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: redis-master
          redis-master: "true"
          redis-sentinel: "true"
          role: master
      spec:
        containers:
        - env:
          - name: MASTER
            value: "true"
          - name: REDIS_DATA_MAX_AGE
            value: ${REDIS_DATA_MAX_AGE}
          image: ${REDIS_IMAGE}
          imagePullPolicy: Always
          name: redis
          ports:
          - containerPort: 6379
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/redis/data
            name: data
        - env:
          - name: SENTINEL
            value: "true"
          image: ${REDIS_IMAGE}
          imagePullPolicy: Always
          name: sentinel
          ports:
          - containerPort: 26379
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${REDIS_PV}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        - sentinel
        from:
          kind: ImageStreamTag
          name: ${REDIS_IMAGE}:${REDIS_IMAGE_TAG}
          namespace: ${REDIS_IMAGE_NAMESPACE}
      type: ImageChange

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${REDIS_PV}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: netapp-file-standard

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: master
      role: service
    name: redis-master
  spec:
    ports:
      - port: 6379
        targetPort: 6379
    selector:
      redis-master: "true"

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: sentinel
      role: service
    name: redis-sentinel
  spec:
    ports:
      - port: 26379
        targetPort: 26379
    selector:
      redis-sentinel: "true"

parameters:
- name: REDIS_DATA_MAX_AGE
  description: Maximal age of slave data directories in days.
  required: true
  value: "4"
- name: REDIS_IMAGE
  description: Location and name of the Redis image.
  required: true
  value: redis-ha
- name: REDIS_IMAGE_NAMESPACE
  description: Namespace to find the Redis image.
  required: true
  value: hdhclr-tools
- name: REDIS_IMAGE_TAG
  description: Tag to use for the Redis image.
  required: true
- name: REDIS_PV
  description: Name of the Redis PV to bind.
  required: true
  value: redis-storage
